# Generated by Django 4.1.3 on 2023-01-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
