# Generated by Django 4.1.3 on 2023-01-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
