# Generated by Django 4.1.3 on 2023-01-22 16:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_end_on_booking_number_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.room_featured_image_path),
        ),
    ]
