# Generated by Django 4.1.3 on 2023-01-23 02:02

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_strength_kitchen_gallery_banner_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.room_featured_image_path),
        ),
        migrations.AddField(
            model_name='strength',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.room_featured_image_path),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default=uuid.uuid1, max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=core.models.room_featured_image_path)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_service', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('approve_service', 'Can approve service'),),
            },
        ),
    ]
