# Generated by Django 4.1.3 on 2023-01-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activity_in_slider_service_in_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='material_icon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
