# Generated by Django 4.1.3 on 2023-01-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_service_material_icon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='strength',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
