# Generated by Django 4.1.3 on 2023-01-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_activity_image_alt_service_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='excerpt1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='excerpt2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
