# Generated by Django 4.1.3 on 2023-01-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_views', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frontend_views',
            field=models.ManyToManyField(blank=True, to='frontend_views.frontendmenulink'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='frontend_views',
            field=models.ManyToManyField(blank=True, to='frontend_views.frontendmenulink'),
        ),
    ]
