# Generated by Django 4.1.3 on 2023-01-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_frontend_views_userrole_frontend_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notified_on_incidents',
            new_name='notified_on_new_booking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notified_on_learning_notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notified_on_stories',
        ),
    ]
