# Generated by Django 4.1.3 on 2023-01-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_notified_on_incidents_user_notified_on_new_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_contact_for_customer_care',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
