# Generated by Django 4.1.3 on 2023-01-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_primary_contact_for_customer_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notified_on_new_booking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_contact_for_customer_care',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
