# Generated by Django 4.1.3 on 2023-01-16 01:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default=uuid.uuid1, max_length=250, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tab', models.CharField(max_length=20)),
                ('codename', models.CharField(max_length=50)),
                ('visibility_code', models.CharField(blank=True, max_length=100, null=True)),
                ('has_link', models.BooleanField(default=True)),
                ('root_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
